name: Build and deploy

on:
    release:
        types: [published]

jobs:
    build:
        strategy:
            matrix:
                platform: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Build and release application
              run: |
                  npm install
                  npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
